using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Golf_Website.Models
{
    public class Scorecard
    {
        public int Id { get; set; }
        public int Par1 { get; set; }
        public int Par2 { get; set; }
        public int Par3 { get; set; }
        public int Par4 { get; set; }
        public int Par5 { get; set; }
        public int Par6 { get; set; }
        public int Par7 { get; set; }
        public int Par8 { get; set; }
        public int Par9 { get; set; }
        public int Par10 { get; set; }
        public int Par11 { get; set; }
        public int Par12 { get; set; }
        public int Par13 { get; set; }
        public int Par14 { get; set; }
        public int Par15 { get; set; }
        public int Par16 { get; set; }
        public int Par17 { get; set; }
        public int Par18 { get; set; }
        public int YardsA1 { get; set; }
        public int YardsB1 { get; set; }
        public int YardsC1 { get; set; }
        public int YardsD1 { get; set; }
        public int YardsA2 { get; set; }
        public int YardsB2 { get; set; }
        public int YardsC2 { get; set; }
        public int YardsD2 { get; set; }
        public int YardsA3 { get; set; }
        public int YardsB3 { get; set; }
        public int YardsC3 { get; set; }
        public int YardsD3 { get; set; }
        public int YardsA4 { get; set; }
        public int YardsB4 { get; set; }
        public int YardsC4 { get; set; }
        public int YardsD4 { get; set; }
        public int YardsA5 { get; set; }
        public int YardsB5 { get; set; }
        public int YardsC5 { get; set; }
        public int YardsD5 { get; set; }
        public int YardsA6 { get; set; }
        public int YardsB6 { get; set; }
        public int YardsC6 { get; set; }
        public int YardsD6 { get; set; }
        public int YardsA7 { get; set; }
        public int YardsB7 { get; set; }
        public int YardsC7 { get; set; }
        public int YardsD7 { get; set; }
        public int YardsA8 { get; set; }
        public int YardsB8 { get; set; }
        public int YardsC8 { get; set; }
        public int YardsD8 { get; set; }
        public int YardsA9 { get; set; }
        public int YardsB9 { get; set; }
        public int YardsC9 { get; set; }
        public int YardsD9 { get; set; }
        public int YardsA10 { get; set; }
        public int YardsB10 { get; set; }
        public int YardsC10 { get; set; }
        public int YardsD10 { get; set; }
        public int YardsA11 { get; set; }
        public int YardsB11 { get; set; }
        public int YardsC11 { get; set; }
        public int YardsD11 { get; set; }
        public int YardsA12 { get; set; }
        public int YardsB12 { get; set; }
        public int YardsC12 { get; set; }
        public int YardsD12 { get; set; }
        public int YardsA13 { get; set; }
        public int YardsB13 { get; set; }
        public int YardsC13 { get; set; }
        public int YardsD13 { get; set; }
        public int YardsA14 { get; set; }
        public int YardsB14 { get; set; }
        public int YardsC14 { get; set; }
        public int YardsD14 { get; set; }
        public int YardsA15 { get; set; }
        public int YardsB15 { get; set; }
        public int YardsC15 { get; set; }
        public int YardsD15 { get; set; }
        public int YardsA16 { get; set; }
        public int YardsB16 { get; set; }
        public int YardsC16 { get; set; }
        public int YardsD16 { get; set; }
        public int YardsA17 { get; set; }
        public int YardsB17 { get; set; }
        public int YardsC17 { get; set; }
        public int YardsD17 { get; set; }
        public int YardsA18 { get; set; }
        public int YardsB18 { get; set; }
        public int YardsC18 { get; set; }
        public int YardsD18 { get; set; }
        public int HandiCap1 { get; set; }
        public int HandiCap2 { get; set; }
        public int HandiCap3 { get; set; }
        public int HandiCap4 { get; set; }
        public int HandiCap5 { get; set; }
        public int HandiCap6 { get; set; }
        public int HandiCap7 { get; set; }
        public int HandiCap8 { get; set; }
        public int HandiCap9 { get; set; }
        public int HandiCap10 { get; set; }
        public int HandiCap11 { get; set; }
        public int HandiCap12 { get; set; }
        public int HandiCap13 { get; set; }
        public int HandiCap14 { get; set; }
        public int HandiCap15 { get; set; }
        public int HandiCap16 { get; set; }
        public int HandiCap17 { get; set; }
        public int HandiCap18 { get; set; }
        public int MyScore1 { get; set; }
        public int MyScore2 { get; set; }
        public int MyScore3 { get; set; }
        public int MyScore4 { get; set; }
        public int MyScore5 { get; set; }
        public int MyScore6 { get; set; }
        public int MyScore7 { get; set; }
        public int MyScore8 { get; set; }
        public int MyScore9 { get; set; }
        public int MyScore10 { get; set; }
        public int MyScore11 { get; set; }
        public int MyScore12 { get; set; }
        public int MyScore13 { get; set; }
        public int MyScore14 { get; set; }
        public int MyScore15 { get; set; }
        public int MyScore16 { get; set; }
        public int MyScore17 { get; set; }
        public int MyScore18 { get; set; }
        public string MyDifficulty { get; set; }
        public int TotalPar { get; set; }
        public int Front { get; set; }
        public int Back { get; set; }
        public int MyTotal { get; set; }
        public int MyFront { get; set; }
        public int MyBack { get; set; }
        public Double HandicapAdj { get; set; }
        public DateTime ScoreDate { get; set; }
        public int CourseId { get; set; }
        public string UserName { get; set; }


    }
}