namespace Golf_Website.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class sc : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Scorecards",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Par1 = c.Int(nullable: false),
                        Par2 = c.Int(nullable: false),
                        Par3 = c.Int(nullable: false),
                        Par4 = c.Int(nullable: false),
                        Par5 = c.Int(nullable: false),
                        Par6 = c.Int(nullable: false),
                        Par7 = c.Int(nullable: false),
                        Par8 = c.Int(nullable: false),
                        Par9 = c.Int(nullable: false),
                        Par10 = c.Int(nullable: false),
                        Par11 = c.Int(nullable: false),
                        Par12 = c.Int(nullable: false),
                        Par13 = c.Int(nullable: false),
                        Par14 = c.Int(nullable: false),
                        Par15 = c.Int(nullable: false),
                        Par16 = c.Int(nullable: false),
                        Par17 = c.Int(nullable: false),
                        Par18 = c.Int(nullable: false),
                        YardsA1 = c.Int(nullable: false),
                        YardsB1 = c.Int(nullable: false),
                        YardsC1 = c.Int(nullable: false),
                        YardsD1 = c.Int(nullable: false),
                        YardsA2 = c.Int(nullable: false),
                        YardsB2 = c.Int(nullable: false),
                        YardsC2 = c.Int(nullable: false),
                        YardsD2 = c.Int(nullable: false),
                        YardsA3 = c.Int(nullable: false),
                        YardsB3 = c.Int(nullable: false),
                        YardsC3 = c.Int(nullable: false),
                        YardsD3 = c.Int(nullable: false),
                        YardsA4 = c.Int(nullable: false),
                        YardsB4 = c.Int(nullable: false),
                        YardsC4 = c.Int(nullable: false),
                        YardsD4 = c.Int(nullable: false),
                        YardsA5 = c.Int(nullable: false),
                        YardsB5 = c.Int(nullable: false),
                        YardsC5 = c.Int(nullable: false),
                        YardsD5 = c.Int(nullable: false),
                        YardsA6 = c.Int(nullable: false),
                        YardsB6 = c.Int(nullable: false),
                        YardsC6 = c.Int(nullable: false),
                        YardsD6 = c.Int(nullable: false),
                        YardsA7 = c.Int(nullable: false),
                        YardsB7 = c.Int(nullable: false),
                        YardsC7 = c.Int(nullable: false),
                        YardsD7 = c.Int(nullable: false),
                        YardsA8 = c.Int(nullable: false),
                        YardsB8 = c.Int(nullable: false),
                        YardsC8 = c.Int(nullable: false),
                        YardsD8 = c.Int(nullable: false),
                        YardsA9 = c.Int(nullable: false),
                        YardsB9 = c.Int(nullable: false),
                        YardsC9 = c.Int(nullable: false),
                        YardsD9 = c.Int(nullable: false),
                        YardsA10 = c.Int(nullable: false),
                        YardsB10 = c.Int(nullable: false),
                        YardsC10 = c.Int(nullable: false),
                        YardsD10 = c.Int(nullable: false),
                        YardsA11 = c.Int(nullable: false),
                        YardsB11 = c.Int(nullable: false),
                        YardsC11 = c.Int(nullable: false),
                        YardsD11 = c.Int(nullable: false),
                        YardsA12 = c.Int(nullable: false),
                        YardsB12 = c.Int(nullable: false),
                        YardsC12 = c.Int(nullable: false),
                        YardsD12 = c.Int(nullable: false),
                        YardsA13 = c.Int(nullable: false),
                        YardsB13 = c.Int(nullable: false),
                        YardsC13 = c.Int(nullable: false),
                        YardsD13 = c.Int(nullable: false),
                        YardsA14 = c.Int(nullable: false),
                        YardsB14 = c.Int(nullable: false),
                        YardsC14 = c.Int(nullable: false),
                        YardsD14 = c.Int(nullable: false),
                        YardsA15 = c.Int(nullable: false),
                        YardsB15 = c.Int(nullable: false),
                        YardsC15 = c.Int(nullable: false),
                        YardsD15 = c.Int(nullable: false),
                        YardsA16 = c.Int(nullable: false),
                        YardsB16 = c.Int(nullable: false),
                        YardsC16 = c.Int(nullable: false),
                        YardsD16 = c.Int(nullable: false),
                        YardsA17 = c.Int(nullable: false),
                        YardsB17 = c.Int(nullable: false),
                        YardsC17 = c.Int(nullable: false),
                        YardsD17 = c.Int(nullable: false),
                        YardsA18 = c.Int(nullable: false),
                        YardsB18 = c.Int(nullable: false),
                        YardsC18 = c.Int(nullable: false),
                        YardsD18 = c.Int(nullable: false),
                        HandiCap1 = c.Int(nullable: false),
                        HandiCap2 = c.Int(nullable: false),
                        HandiCap3 = c.Int(nullable: false),
                        HandiCap4 = c.Int(nullable: false),
                        HandiCap5 = c.Int(nullable: false),
                        HandiCap6 = c.Int(nullable: false),
                        HandiCap7 = c.Int(nullable: false),
                        HandiCap8 = c.Int(nullable: false),
                        HandiCap9 = c.Int(nullable: false),
                        HandiCap10 = c.Int(nullable: false),
                        HandiCap11 = c.Int(nullable: false),
                        HandiCap12 = c.Int(nullable: false),
                        HandiCap13 = c.Int(nullable: false),
                        HandiCap14 = c.Int(nullable: false),
                        HandiCap15 = c.Int(nullable: false),
                        HandiCap16 = c.Int(nullable: false),
                        HandiCap17 = c.Int(nullable: false),
                        HandiCap18 = c.Int(nullable: false),
                        MyScore1 = c.Int(nullable: false),
                        MyScore2 = c.Int(nullable: false),
                        MyScore3 = c.Int(nullable: false),
                        MyScore4 = c.Int(nullable: false),
                        MyScore5 = c.Int(nullable: false),
                        MyScore6 = c.Int(nullable: false),
                        MyScore7 = c.Int(nullable: false),
                        MyScore8 = c.Int(nullable: false),
                        MyScore9 = c.Int(nullable: false),
                        MyScore10 = c.Int(nullable: false),
                        MyScore11 = c.Int(nullable: false),
                        MyScore12 = c.Int(nullable: false),
                        MyScore13 = c.Int(nullable: false),
                        MyScore14 = c.Int(nullable: false),
                        MyScore15 = c.Int(nullable: false),
                        MyScore16 = c.Int(nullable: false),
                        MyScore17 = c.Int(nullable: false),
                        MyScore18 = c.Int(nullable: false),
                        MyDifficulty = c.Int(nullable: false),
                        CourseId = c.Int(nullable: false),
                        UserId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.Scorecards");
        }
    }
}
