// <auto-generated />
namespace Golf_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newTees1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newTees1));
        
        string IMigrationMetadata.Id
        {
            get { return "201601270003436_newTees1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
